---
Metrics/LineLength:
  Enabled: true
  Max: 119

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NegatedIf:
  Enabled: false

NilCheck:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
