---

AllCops:
  TargetRubyVersion: 2.5

# Since we're not using VT220s we can allow a slightly longer line length
Metrics/LineLength:
  Enabled: true
  Max: 119

# You're fucking shitting me.
Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/AbcSize:
  Enabled: true
  Max: 35

# Any Ruby DSL defined by closures will cause this metric to fail
Metrics/BlockLength:
  Enabled: false

# Pedantic/noisy
Style/StringLiterals:
  Enabled: false

# `unless` is overly clever; negatived if expressions are easier to reason about.
Style/NegatedIf:
  Enabled: false

# NilChecks are better than blind boolean expressions; `false` is valid in many contexts.
Style/NilCheck:
  Enabled: false

# Overly noisy, no value provided
Style/NumericPredicate:
  Enabled: false

# Overly pedantic
Bundler/OrderedGems:
  Enabled: false

# Overly noisy
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/FormatString:
  Enabled: false

# conflicts with r10k
Style/ClassAndModuleChildren:
  Enabled: false

# #inject() 4 lyfe
Style/EachWithObject:
  Enabled: false
